apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: spring-boot-hello
  template:
    metadata:
      labels:
        app: spring-boot-hello
    spec:
      containers:
        - name: spring-cloud-discovery
          image: vamsitechtuts/spring-boot-hello:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
